service: feedIndexer

# use the stage from the cli if provided, otherwise fallback to the one in provider
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  domainName: ${opt:domain, self:provider.domain}
  indexName: ${self:service}_${self:custom.stage}_content

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "elasticSearch:*"
      Resource: "arn:aws:es:${self:custom.region}:*:domain/${self:custom.domainName}"

  environment:
    INDEX_NAME: ${self:custom.indexName}

  stage: dev
  region: eu-west-2
  domain: content

package:
  exclude:
    - .idea/**
    - .npmignore
    - package.json
    - node_modules/**
    - tests/**
    - README.md

functions:
  indexer:
    handler: functions/indexer.handler
    events:
      - schedule : rate(1 minutes)

  filter:
    handler: functions/filter.handler
    events:
      - http:
          path: /filter
          method: get

resources:
  Resources:
    feedIndex:
      Type: AWS::Elasticsearch::Domain
      Properties:
        DomainName: ${self:custom.domainName}
        ElasticsearchVersion: 5.1
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
        EBSOptions:
          EBSEnabled: true
          VolumeSize: 10
          VolumeType: "gp2"
